### ISSUE TITLE
Editing/deleting servers doesn't work

### ISSUE THREAD

**Issue by Brueggus** [iandk/servermanager#2]
Hi,
I can't reply to the other issue anymore so I'm opening a new one...

I'm not sure whether this is related to the recent switch to ids for indexing servers, but I cannot edit/delete servers anymore. When I try to edit a server, the form pops up but stays empty. I've attached the data I use.

[data.tar.gz](https://github.com/iandk/servermanager/files/6042525/data.tar.gz)

**Comment by iandk** [comment]
Hey there, 

The switch to unique IDs requires a reinstall and adding the hosts again.
It's unfortunately not possible to use the existing hosts since the naming format has changed.

Please try to download the latest version from github and add your hosts again.
Oh and make sure to delete your browser cache.

Let me know if this solves the issue for you.


Cheers

**Comment by Brueggus** [comment]
My bad... sorry. I pulled the repo again but didn't sync it to the web server properly...

Everything's working fine! :+1:
